set_property IOSTANDARD LVTTL [get_ports gt_in]
set_property IOSTANDARD LVTTL [get_ports trig_out]
set_property IOSTANDARD LVTTL [get_ports {mtca_mimic_in[0]}]
set_property IOSTANDARD LVTTL [get_ports {mtca_mimic_in[1]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[0]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[1]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[2]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[3]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[4]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[5]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[6]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[7]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[8]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[9]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[10]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[11]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[12]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[13]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[14]}]
set_property IOSTANDARD LVTTL [get_ports {ext_trig_in[15]}]
set_property PACKAGE_PIN D19 [get_ports gt_in]
set_property PACKAGE_PIN W13 [get_ports trig_out]
set_property PACKAGE_PIN F16 [get_ports {mtca_mimic_in[0]}]
set_property PACKAGE_PIN D20 [get_ports {mtca_mimic_in[1]}]
set_property PACKAGE_PIN P16 [get_ports {ext_trig_in[0]}]
set_property PACKAGE_PIN P15 [get_ports {ext_trig_in[1]}]
set_property PACKAGE_PIN W19 [get_ports {ext_trig_in[2]}]
set_property PACKAGE_PIN W18 [get_ports {ext_trig_in[3]}]
set_property PACKAGE_PIN R18 [get_ports {ext_trig_in[4]}]
set_property PACKAGE_PIN T17 [get_ports {ext_trig_in[5]}]
set_property PACKAGE_PIN W16 [get_ports {ext_trig_in[6]}]
set_property PACKAGE_PIN V16 [get_ports {ext_trig_in[7]}]
set_property PACKAGE_PIN G19 [get_ports {ext_trig_in[8]}]
set_property PACKAGE_PIN G18 [get_ports {ext_trig_in[9]}]
set_property PACKAGE_PIN G17 [get_ports {ext_trig_in[10]}]
set_property PACKAGE_PIN G20 [get_ports {ext_trig_in[11]}]
set_property PACKAGE_PIN N15 [get_ports {ext_trig_in[12]}]
set_property PACKAGE_PIN J14 [get_ports {ext_trig_in[13]}]
set_property PACKAGE_PIN K14 [get_ports {ext_trig_in[14]}]
set_property PACKAGE_PIN N16 [get_ports {ext_trig_in[15]}]

set_property IOSTANDARD LVTTL [get_ports sync]
set_property IOSTANDARD LVTTL [get_ports sync24]
set_property PACKAGE_PIN A20 [get_ports sync]
set_property PACKAGE_PIN B19 [get_ports sync24]

set_property IOSTANDARD LVTTL [get_ports display_count]
set_property IOSTANDARD LVTTL [get_ports display_latch]
set_property IOSTANDARD LVTTL [get_ports display_reset]
set_property PACKAGE_PIN P14 [get_ports display_count]
set_property PACKAGE_PIN W14 [get_ports display_latch]
set_property PACKAGE_PIN R14 [get_ports display_reset]

set_property IOSTANDARD LVTTL [get_ports speaker]
set_property PACKAGE_PIN K19 [get_ports speaker]

set_property IOSTANDARD LVTTL [get_ports generic_delay_in]
set_property IOSTANDARD LVTTL [get_ports generic_pulser_out]
set_property IOSTANDARD LVTTL [get_ports generic_delay_out]
set_property PACKAGE_PIN E17 [get_ports generic_delay_in]
set_property PACKAGE_PIN V13 [get_ports generic_pulser_out]
set_property PACKAGE_PIN T14 [get_ports generic_delay_out]

set_property IOSTANDARD LVTTL [get_ports tellie_delay_in]
set_property IOSTANDARD LVTTL [get_ports tellie_pulser_out]
set_property IOSTANDARD LVTTL [get_ports tellie_delay_out]
set_property PACKAGE_PIN B20 [get_ports tellie_delay_in]
set_property PACKAGE_PIN J19 [get_ports tellie_pulser_out]
set_property PACKAGE_PIN K18 [get_ports tellie_delay_out]

set_property IOSTANDARD LVTTL [get_ports smellie_delay_in]
set_property IOSTANDARD LVTTL [get_ports smellie_pulser_out]
set_property IOSTANDARD LVTTL [get_ports smellie_delay_out]
set_property PACKAGE_PIN C20 [get_ports smellie_delay_in]
set_property PACKAGE_PIN K17 [get_ports smellie_pulser_out]
set_property PACKAGE_PIN J18 [get_ports smellie_delay_out]

set_property IOSTANDARD LVTTL [get_ports enablemux]
set_property IOSTANDARD LVTTL [get_ports {muxer[2]}]
set_property IOSTANDARD LVTTL [get_ports {muxer[1]}]
set_property IOSTANDARD LVTTL [get_ports {muxer[0]}]
set_property PACKAGE_PIN H17 [get_ports enablemux]
set_property PACKAGE_PIN H16 [get_ports {muxer[2]}]
set_property PACKAGE_PIN L17 [get_ports {muxer[1]}]
set_property PACKAGE_PIN L16 [get_ports {muxer[0]}]

set_property IOSTANDARD LVTTL [get_ports load_clk_out]
set_property IOSTANDARD LVTTL [get_ports load_data_out]
set_property PACKAGE_PIN M20 [get_ports load_clk_out]
set_property PACKAGE_PIN M19 [get_ports load_data_out]

set_property IOSTANDARD LVTTL [get_ports read_clk_out]
set_property IOSTANDARD LVTTL [get_ports read_data_in]
set_property PACKAGE_PIN V15 [get_ports read_clk_out]
set_property PACKAGE_PIN Y14 [get_ports read_data_in]

set_property IOSTANDARD LVTTL [get_ports control_rdy]
set_property IOSTANDARD LVTTL [get_ports caen_rdy]
set_property IOSTANDARD LVTTL [get_ports mtcamimic_rdy]
set_property IOSTANDARD LVTTL [get_ports clocks_rdy]
set_property PACKAGE_PIN P18 [get_ports control_rdy]
set_property PACKAGE_PIN U13 [get_ports caen_rdy]
set_property PACKAGE_PIN F17 [get_ports mtcamimic_rdy]
set_property PACKAGE_PIN T15 [get_ports clocks_rdy]

set_property IOSTANDARD LVTTL [get_ports Clk_in]
set_property IOSTANDARD LVTTL [get_ports backup_clk_in_use]
set_property IOSTANDARD LVTTL [get_ports reset_clk]
set_property PACKAGE_PIN U14 [get_ports Clk_in]
set_property PACKAGE_PIN N17 [get_ports backup_clk_in_use]
set_property PACKAGE_PIN N18 [get_ports reset_clk]

set_property IOSTANDARD LVTTL [get_ports MZ_Happy]
set_property PACKAGE_PIN V12 [get_ports MZ_Happy]

set_property IOSTANDARD LVTTL [get_ports delay_gt]
set_property PACKAGE_PIN L15 [get_ports delay_gt]

set_property IOSTANDARD LVTTL [get_ports Outt]
set_property PACKAGE_PIN U15 [get_ports Outt]
set_property IOSTANDARD LVTTL [get_ports Outtt]
set_property PACKAGE_PIN U19 [get_ports Outtt]
