# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  c:/Users/Ian/project_tubii_7020/testFIFO_1.0
  c:/Users/Ian/project_tubii_7020/tubiiFIFO_1.0
  c:/Users/Ian/project_tubii_7020/nothing_1.0
  c:/Users/Ian/project_tubii_7020/masterOut_1.0
  c:/Users/Ian/project_tubii_7020/testmaster_1.0
  c:/Users/Ian/project_tubii_7020/testPulser_1.0
  c:/Users/Ian/project_tubii_7020/triggerOut_1.0
  c:/Users/Ian/project_tubii_7020/clockLogic_1.0
  c:/Users/Ian/project_tubii_7020/triggerSplit_1.0
  c:/Users/Ian/project_tubii_7020
} [current_fileset]
read_vhdl {
  c:/Users/Ian/project_tubii_7020/testFIFO_1.0/hdl/testFIFO_v1_0_S00_AXI.vhd
  c:/Users/Ian/project_tubii_7020/testFIFO_1.0/hdl/testFIFO_v1_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ian/project_tubii_7020/edit_testFIFO_v1_0.data/wt [current_project]
set_property parent.project_dir C:/Users/Ian/project_tubii_7020 [current_project]
synth_design -top testFIFO_v1_0 -part xc7z020clg400-1
write_checkpoint testFIFO_v1_0.dcp
report_utilization -file testFIFO_v1_0_utilization_synth.rpt -pb testFIFO_v1_0_utilization_synth.pb
