# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  C:/Users/Ian/project_tubii/tubiiDelay_2.0
  C:/Users/Ian/project_tubii/clockLogic_1.0
  C:/Users/Ian/project_tubii/burstTrigger_1.0
  C:/Users/Ian/project_tubii/prescaleTrigger_1.0
  C:/Users/Ian/project_tubii/comboTrigger_1.0
  C:/Users/Ian/project_tubii/testFanIn_1.0
  C:/Users/Ian/project_tubii/testDelay_1.0
  C:/Users/Ian/project_tubii/testPulser_1.0
  C:/Users/Ian/project_tubii/testtubii_1.0
} [current_fileset]
read_vhdl {
  C:/Users/Ian/project_tubii/tubiiDelay_2.0/hdl/tubiiDelay_v2_0_S00_AXI.vhd
  C:/Users/Ian/project_tubii/tubiiDelay_2.0/hdl/tubiiDelay_v2_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ian/project_tubii/tubiiDelay_2.0/tubiiDelay_v2_0_project/tubiiDelay_v2_0_project.data/wt [current_project]
set_property parent.project_dir C:/Users/Ian/project_tubii/tubiiDelay_2.0/tubiiDelay_v2_0_project [current_project]
synth_design -top tubiiDelay_v2_0 -part xc7z010clg400-1
write_checkpoint tubiiDelay_v2_0.dcp
report_utilization -file tubiiDelay_v2_0_utilization_synth.rpt -pb tubiiDelay_v2_0_utilization_synth.pb
