# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_comboTrigger_0_0/system_comboTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_comboTrigger_0_0 || ORIG_REF_NAME==system_comboTrigger_0_0}]

# IP: bd/system/ip/system_burstTrigger_0_0/system_burstTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_burstTrigger_0_0 || ORIG_REF_NAME==system_burstTrigger_0_0}]

# IP: bd/system/ip/system_prescaleTrigger_0_0/system_prescaleTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_prescaleTrigger_0_0 || ORIG_REF_NAME==system_prescaleTrigger_0_0}]

# IP: bd/system/ip/system_countDisplay_0_0/system_countDisplay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_countDisplay_0_0 || ORIG_REF_NAME==system_countDisplay_0_0}]

# IP: bd/system/ip/system_clockLogic_0_0/system_clockLogic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clockLogic_0_0 || ORIG_REF_NAME==system_clockLogic_0_0}]

# IP: bd/system/ip/system_testDelay_0_0/system_testDelay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_0_0 || ORIG_REF_NAME==system_testDelay_0_0}]

# IP: bd/system/ip/system_testDelay_2_5/system_testDelay_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_2_5 || ORIG_REF_NAME==system_testDelay_2_5}]

# IP: bd/system/ip/system_testDelay_3_6/system_testDelay_3_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_3_6 || ORIG_REF_NAME==system_testDelay_3_6}]

# IP: bd/system/ip/system_testPulser_0_7/system_testPulser_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_7 || ORIG_REF_NAME==system_testPulser_0_7}]

# IP: bd/system/ip/system_testDelay_0_7/system_testDelay_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_0_7 || ORIG_REF_NAME==system_testDelay_0_7}]

# IP: bd/system/ip/system_testPulser_0_9/system_testPulser_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_9 || ORIG_REF_NAME==system_testPulser_0_9}]

# IP: bd/system/ip/system_testPulser_0_10/system_testPulser_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_10 || ORIG_REF_NAME==system_testPulser_0_10}]

# IP: bd/system/ip/system_testPulser_1_11/system_testPulser_1_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_1_11 || ORIG_REF_NAME==system_testPulser_1_11}]

# IP: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_generator_0_0 || ORIG_REF_NAME==system_fifo_generator_0_0}]

# IP: bd/system/ip/system_fifo_readout_0_0/system_fifo_readout_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_readout_0_0 || ORIG_REF_NAME==system_fifo_readout_0_0}]

# IP: bd/system/ip/system_oneshot_pulse_1_1/system_oneshot_pulse_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_oneshot_pulse_1_1 || ORIG_REF_NAME==system_oneshot_pulse_1_1}]

# IP: bd/system/ip/system_oneshot_pulse_0_2/system_oneshot_pulse_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_oneshot_pulse_0_2 || ORIG_REF_NAME==system_oneshot_pulse_0_2}]

# IP: bd/system/ip/system_implement_gtid_0_0/system_implement_gtid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_implement_gtid_0_0 || ORIG_REF_NAME==system_implement_gtid_0_0}]

# IP: bd/system/ip/system_auto_cc_5_0/system_auto_cc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_5 || ORIG_REF_NAME==system_auto_cc_5}]

# IP: bd/system/ip/system_ShiftRegisters_0_0/system_ShiftRegisters_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ShiftRegisters_0_0 || ORIG_REF_NAME==system_ShiftRegisters_0_0}]

# IP: bd/system/ip/system_triggers_0_0/system_triggers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_triggers_0_0 || ORIG_REF_NAME==system_triggers_0_0}]

# IP: bd/system/ip/system_auto_pc_44_0/system_auto_pc_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_44 || ORIG_REF_NAME==system_auto_pc_44}]

# IP: bd/system/ip/system_auto_cc_408_0/system_auto_cc_408.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_408 || ORIG_REF_NAME==system_auto_cc_408}]

# IP: bd/system/ip/system_auto_cc_410_0/system_auto_cc_410.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_410 || ORIG_REF_NAME==system_auto_cc_410}]

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0}]

# IP: bd/system/ip/system_util_reduced_logic_0_0/system_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_0_0 || ORIG_REF_NAME==system_util_reduced_logic_0_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_xlconcat_1_6/system_xlconcat_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_1_6 || ORIG_REF_NAME==system_xlconcat_1_6}]

# IP: bd/system/ip/system_util_vector_logic_1_1/system_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_1_1 || ORIG_REF_NAME==system_util_vector_logic_1_1}]

# IP: bd/system/ip/system_util_reduced_logic_1_1/system_util_reduced_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_1_1 || ORIG_REF_NAME==system_util_reduced_logic_1_1}]

# IP: bd/system/ip/system_util_vector_logic_2_2/system_util_vector_logic_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_2_2 || ORIG_REF_NAME==system_util_vector_logic_2_2}]

# IP: bd/system/ip/system_util_reduced_logic_2_2/system_util_reduced_logic_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_2_2 || ORIG_REF_NAME==system_util_reduced_logic_2_2}]

# IP: bd/system/ip/system_auto_cc_411_1/system_auto_cc_411.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_411 || ORIG_REF_NAME==system_auto_cc_411}]

# IP: bd/system/ip/system_auto_cc_412_1/system_auto_cc_412.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_412 || ORIG_REF_NAME==system_auto_cc_412}]

# IP: bd/system/ip/system_auto_cc_413_1/system_auto_cc_413.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_413 || ORIG_REF_NAME==system_auto_cc_413}]

# IP: bd/system/ip/system_auto_cc_414_1/system_auto_cc_414.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_414 || ORIG_REF_NAME==system_auto_cc_414}]

# IP: bd/system/ip/system_auto_cc_415_1/system_auto_cc_415.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_415 || ORIG_REF_NAME==system_auto_cc_415}]

# IP: bd/system/ip/system_auto_cc_416_1/system_auto_cc_416.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_416 || ORIG_REF_NAME==system_auto_cc_416}]

# IP: bd/system/ip/system_auto_cc_417_1/system_auto_cc_417.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_417 || ORIG_REF_NAME==system_auto_cc_417}]

# IP: bd/system/ip/system_auto_cc_418_1/system_auto_cc_418.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_418 || ORIG_REF_NAME==system_auto_cc_418}]

# IP: bd/system/ip/system_auto_cc_419_1/system_auto_cc_419.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_419 || ORIG_REF_NAME==system_auto_cc_419}]

# IP: bd/system/ip/system_auto_cc_420_1/system_auto_cc_420.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_420 || ORIG_REF_NAME==system_auto_cc_420}]

# IP: bd/system/ip/system_auto_pc_82_0/system_auto_pc_82.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_82 || ORIG_REF_NAME==system_auto_pc_82}]

# IP: bd/system/ip/system_tier2_xbar_0_1325_0/system_tier2_xbar_0_1325.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_1325 || ORIG_REF_NAME==system_tier2_xbar_0_1325}]

# IP: bd/system/ip/system_tier2_xbar_1_1326_0/system_tier2_xbar_1_1326.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_1326 || ORIG_REF_NAME==system_tier2_xbar_1_1326}]

# IP: bd/system/ip/system_tier2_xbar_2_1327_0/system_tier2_xbar_2_1327.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_1327 || ORIG_REF_NAME==system_tier2_xbar_2_1327}]

# IP: bd/system/ip/system_auto_cc_421_0/system_auto_cc_421.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_421 || ORIG_REF_NAME==system_auto_cc_421}]

# IP: bd/system/ip/system_auto_cc_422_0/system_auto_cc_422.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_422 || ORIG_REF_NAME==system_auto_cc_422}]

# IP: bd/system/ip/system_auto_cc_423_0/system_auto_cc_423.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_423 || ORIG_REF_NAME==system_auto_cc_423}]

# IP: bd/system/ip/system_auto_cc_424_0/system_auto_cc_424.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_424 || ORIG_REF_NAME==system_auto_cc_424}]

# IP: bd/system/ip/system_auto_cc_425_0/system_auto_cc_425.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_425 || ORIG_REF_NAME==system_auto_cc_425}]

# IP: bd/system/ip/system_auto_pc_83_0/system_auto_pc_83.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_83 || ORIG_REF_NAME==system_auto_pc_83}]

# IP: bd/system/ip/system_prescaleSignal_0_0/system_prescaleSignal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_prescaleSignal_0_0 || ORIG_REF_NAME==system_prescaleSignal_0_0}]

# IP: bd/system/ip/system_auto_cc_507_0/system_auto_cc_507.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_507 || ORIG_REF_NAME==system_auto_cc_507}]

# IP: bd/system/ip/system_auto_cc_511_0/system_auto_cc_511.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_511 || ORIG_REF_NAME==system_auto_cc_511}]

# IP: bd/system/ip/system_auto_pc_100_0/system_auto_pc_100.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_100 || ORIG_REF_NAME==system_auto_pc_100}]

# IP: bd/system/ip/system_tier2_xbar_0_1385_0/system_tier2_xbar_0_1385.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_1385 || ORIG_REF_NAME==system_tier2_xbar_0_1385}]

# IP: bd/system/ip/system_tier2_xbar_1_1386_0/system_tier2_xbar_1_1386.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_1386 || ORIG_REF_NAME==system_tier2_xbar_1_1386}]

# IP: bd/system/ip/system_tier2_xbar_2_1387_0/system_tier2_xbar_2_1387.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_1387 || ORIG_REF_NAME==system_tier2_xbar_2_1387}]

# IP: bd/system/ip/system_auto_cc_512_0/system_auto_cc_512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_512 || ORIG_REF_NAME==system_auto_cc_512}]

# IP: bd/system/ip/system_auto_cc_513_0/system_auto_cc_513.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_513 || ORIG_REF_NAME==system_auto_cc_513}]

# IP: bd/system/ip/system_auto_cc_514_0/system_auto_cc_514.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_514 || ORIG_REF_NAME==system_auto_cc_514}]

# IP: bd/system/ip/system_auto_cc_515_0/system_auto_cc_515.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_515 || ORIG_REF_NAME==system_auto_cc_515}]

# IP: bd/system/ip/system_auto_pc_101_0/system_auto_pc_101.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_101 || ORIG_REF_NAME==system_auto_pc_101}]

# IP: bd/system/ip/system_util_vector_logic_3_3/system_util_vector_logic_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_3_3 || ORIG_REF_NAME==system_util_vector_logic_3_3}]

# IP: bd/system/ip/system_util_vector_logic_4_4/system_util_vector_logic_4_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_4_4 || ORIG_REF_NAME==system_util_vector_logic_4_4}]

# IP: bd/system/ip/system_util_reduced_logic_3_3/system_util_reduced_logic_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_3_3 || ORIG_REF_NAME==system_util_reduced_logic_3_3}]

# IP: bd/system/ip/system_util_vector_logic_5_5/system_util_vector_logic_5_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_5_5 || ORIG_REF_NAME==system_util_vector_logic_5_5}]

# IP: bd/system/ip/system_util_reduced_logic_4_4/system_util_reduced_logic_4_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_4_4 || ORIG_REF_NAME==system_util_reduced_logic_4_4}]

# IP: bd/system/ip/system_prescaleSignal_1_1/system_prescaleSignal_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_prescaleSignal_1_1 || ORIG_REF_NAME==system_prescaleSignal_1_1}]

# IP: bd/system/ip/system_util_vector_logic_6_6/system_util_vector_logic_6_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_6_6 || ORIG_REF_NAME==system_util_vector_logic_6_6}]

# IP: bd/system/ip/system_util_vector_logic_7_7/system_util_vector_logic_7_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_7_7 || ORIG_REF_NAME==system_util_vector_logic_7_7}]

# IP: bd/system/ip/system_util_reduced_logic_5_5/system_util_reduced_logic_5_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_5_5 || ORIG_REF_NAME==system_util_reduced_logic_5_5}]

# IP: bd/system/ip/system_util_vector_logic_8_8/system_util_vector_logic_8_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_8_8 || ORIG_REF_NAME==system_util_vector_logic_8_8}]

# IP: bd/system/ip/system_util_reduced_logic_6_6/system_util_reduced_logic_6_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_reduced_logic_6_6 || ORIG_REF_NAME==system_util_reduced_logic_6_6}]

# IP: bd/system/ip/system_util_vector_logic_9_9/system_util_vector_logic_9_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_9_9 || ORIG_REF_NAME==system_util_vector_logic_9_9}]

# IP: bd/system/ip/system_tier2_xbar_0_1487_0/system_tier2_xbar_0_1487.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_1487 || ORIG_REF_NAME==system_tier2_xbar_0_1487}]

# IP: bd/system/ip/system_tier2_xbar_1_1488_0/system_tier2_xbar_1_1488.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_1488 || ORIG_REF_NAME==system_tier2_xbar_1_1488}]

# IP: bd/system/ip/system_tier2_xbar_2_1489_0/system_tier2_xbar_2_1489.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_1489 || ORIG_REF_NAME==system_tier2_xbar_2_1489}]

# IP: bd/system/ip/system_auto_pc_134_0/system_auto_pc_134.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_134 || ORIG_REF_NAME==system_auto_pc_134}]

# IP: bd/system/ip/system_testPulser_0_12/system_testPulser_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_12 || ORIG_REF_NAME==system_testPulser_0_12}]

# IP: bd/system/ip/system_fifo_generator_1_1/system_fifo_generator_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_generator_1_1 || ORIG_REF_NAME==system_fifo_generator_1_1}]

# IP: bd/system/ip/system_trigwordfifo_0_0/system_trigwordfifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_trigwordfifo_0_0 || ORIG_REF_NAME==system_trigwordfifo_0_0}]

# IP: bd/system/ip/system_auto_cc_957/system_auto_cc_957.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_957 || ORIG_REF_NAME==system_auto_cc_957}]

# IP: bd/system/ip/system_auto_cc_967/system_auto_cc_967.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_967 || ORIG_REF_NAME==system_auto_cc_967}]

# IP: bd/system/ip/system_auto_cc_975/system_auto_cc_975.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_975 || ORIG_REF_NAME==system_auto_cc_975}]

# IP: bd/system/ip/system_util_vector_logic_10_10/system_util_vector_logic_10_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_10_10 || ORIG_REF_NAME==system_util_vector_logic_10_10}]

# IP: bd/system/ip/system_util_vector_logic_11_11/system_util_vector_logic_11_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_11_11 || ORIG_REF_NAME==system_util_vector_logic_11_11}]

# IP: bd/system/ip/system_util_vector_logic_12_12/system_util_vector_logic_12_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_12_12 || ORIG_REF_NAME==system_util_vector_logic_12_12}]

# IP: bd/system/ip/system_util_vector_logic_13_13/system_util_vector_logic_13_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_vector_logic_13_13 || ORIG_REF_NAME==system_util_vector_logic_13_13}]

# IP: bd/system/ip/system_ellie_control_0_0/system_ellie_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ellie_control_0_0 || ORIG_REF_NAME==system_ellie_control_0_0}]

# IP: bd/system/ip/system_tier2_xbar_0_1577/system_tier2_xbar_0_1577.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_1577 || ORIG_REF_NAME==system_tier2_xbar_0_1577}]

# IP: bd/system/ip/system_tier2_xbar_1_1578/system_tier2_xbar_1_1578.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_1578 || ORIG_REF_NAME==system_tier2_xbar_1_1578}]

# IP: bd/system/ip/system_tier2_xbar_2_1579/system_tier2_xbar_2_1579.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_1579 || ORIG_REF_NAME==system_tier2_xbar_2_1579}]

# IP: bd/system/ip/system_auto_cc_1019/system_auto_cc_1019.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1019 || ORIG_REF_NAME==system_auto_cc_1019}]

# IP: bd/system/ip/system_auto_cc_1020/system_auto_cc_1020.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1020 || ORIG_REF_NAME==system_auto_cc_1020}]

# IP: bd/system/ip/system_auto_cc_1021/system_auto_cc_1021.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1021 || ORIG_REF_NAME==system_auto_cc_1021}]

# IP: bd/system/ip/system_auto_cc_1022/system_auto_cc_1022.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1022 || ORIG_REF_NAME==system_auto_cc_1022}]

# IP: bd/system/ip/system_auto_cc_1023/system_auto_cc_1023.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1023 || ORIG_REF_NAME==system_auto_cc_1023}]

# IP: bd/system/ip/system_auto_cc_1024/system_auto_cc_1024.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1024 || ORIG_REF_NAME==system_auto_cc_1024}]

# IP: bd/system/ip/system_auto_cc_1025/system_auto_cc_1025.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1025 || ORIG_REF_NAME==system_auto_cc_1025}]

# IP: bd/system/ip/system_auto_cc_1026/system_auto_cc_1026.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1026 || ORIG_REF_NAME==system_auto_cc_1026}]

# IP: bd/system/ip/system_auto_cc_1027/system_auto_cc_1027.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1027 || ORIG_REF_NAME==system_auto_cc_1027}]

# IP: bd/system/ip/system_auto_cc_1028/system_auto_cc_1028.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1028 || ORIG_REF_NAME==system_auto_cc_1028}]

# IP: bd/system/ip/system_auto_cc_1029/system_auto_cc_1029.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1029 || ORIG_REF_NAME==system_auto_cc_1029}]

# IP: bd/system/ip/system_auto_cc_1030/system_auto_cc_1030.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1030 || ORIG_REF_NAME==system_auto_cc_1030}]

# IP: bd/system/ip/system_auto_cc_1031/system_auto_cc_1031.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1031 || ORIG_REF_NAME==system_auto_cc_1031}]

# IP: bd/system/ip/system_auto_cc_1032/system_auto_cc_1032.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1032 || ORIG_REF_NAME==system_auto_cc_1032}]

# IP: bd/system/ip/system_auto_pc_163/system_auto_pc_163.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_163 || ORIG_REF_NAME==system_auto_pc_163}]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0/system_fifo_generator_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_generator_0_0 || ORIG_REF_NAME==system_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0/system_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_generator_0_0 || ORIG_REF_NAME==system_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_5_0/system_auto_cc_5_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_5_0/system_auto_cc_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_5 || ORIG_REF_NAME==system_auto_cc_5}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_fifo_generator_1_1/system_fifo_generator_1_1/system_fifo_generator_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_generator_1_1 || ORIG_REF_NAME==system_fifo_generator_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_fifo_generator_1_1/system_fifo_generator_1_1_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_0_1577/system_tier2_xbar_0_1577_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_1_1578/system_tier2_xbar_1_1578_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_2_1579/system_tier2_xbar_2_1579_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1019/system_auto_cc_1019_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1019/system_auto_cc_1019_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1019 || ORIG_REF_NAME==system_auto_cc_1019}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1020/system_auto_cc_1020_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1020/system_auto_cc_1020_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1020 || ORIG_REF_NAME==system_auto_cc_1020}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1021/system_auto_cc_1021_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1021/system_auto_cc_1021_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1021 || ORIG_REF_NAME==system_auto_cc_1021}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1022/system_auto_cc_1022_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1022/system_auto_cc_1022_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1022 || ORIG_REF_NAME==system_auto_cc_1022}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1023/system_auto_cc_1023_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1023/system_auto_cc_1023_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1023 || ORIG_REF_NAME==system_auto_cc_1023}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1024/system_auto_cc_1024_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1024/system_auto_cc_1024_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1024 || ORIG_REF_NAME==system_auto_cc_1024}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1025/system_auto_cc_1025_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1025/system_auto_cc_1025_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1025 || ORIG_REF_NAME==system_auto_cc_1025}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1026/system_auto_cc_1026_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1026/system_auto_cc_1026_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1026 || ORIG_REF_NAME==system_auto_cc_1026}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1027/system_auto_cc_1027_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1027/system_auto_cc_1027_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1027 || ORIG_REF_NAME==system_auto_cc_1027}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1028/system_auto_cc_1028_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1028/system_auto_cc_1028_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1028 || ORIG_REF_NAME==system_auto_cc_1028}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1029/system_auto_cc_1029_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1029/system_auto_cc_1029_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1029 || ORIG_REF_NAME==system_auto_cc_1029}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1030/system_auto_cc_1030_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1030/system_auto_cc_1030_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1030 || ORIG_REF_NAME==system_auto_cc_1030}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1031/system_auto_cc_1031_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1031/system_auto_cc_1031_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1031 || ORIG_REF_NAME==system_auto_cc_1031}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_1032/system_auto_cc_1032_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_1032/system_auto_cc_1032_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_1032 || ORIG_REF_NAME==system_auto_cc_1032}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_163/system_auto_pc_163_ooc.xdc

# XDC: bd/system/system_ooc.xdc
