# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0}]

# IP: bd/system/ip/system_triggerSplit_0_0/system_triggerSplit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_triggerSplit_0_0 || ORIG_REF_NAME==system_triggerSplit_0_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_comboTrigger_0_0/system_comboTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_comboTrigger_0_0 || ORIG_REF_NAME==system_comboTrigger_0_0}]

# IP: bd/system/ip/system_burstTrigger_0_0/system_burstTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_burstTrigger_0_0 || ORIG_REF_NAME==system_burstTrigger_0_0}]

# IP: bd/system/ip/system_prescaleTrigger_0_0/system_prescaleTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_prescaleTrigger_0_0 || ORIG_REF_NAME==system_prescaleTrigger_0_0}]

# IP: bd/system/ip/system_countDisplay_0_0/system_countDisplay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_countDisplay_0_0 || ORIG_REF_NAME==system_countDisplay_0_0}]

# IP: bd/system/ip/system_clockLogic_0_0/system_clockLogic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clockLogic_0_0 || ORIG_REF_NAME==system_clockLogic_0_0}]

# IP: bd/system/ip/system_testDelay_0_0/system_testDelay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_0_0 || ORIG_REF_NAME==system_testDelay_0_0}]

# IP: bd/system/ip/system_testDelay_2_5/system_testDelay_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_2_5 || ORIG_REF_NAME==system_testDelay_2_5}]

# IP: bd/system/ip/system_testDelay_3_6/system_testDelay_3_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_3_6 || ORIG_REF_NAME==system_testDelay_3_6}]

# IP: bd/system/ip/system_testPulser_0_7/system_testPulser_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_7 || ORIG_REF_NAME==system_testPulser_0_7}]

# IP: bd/system/ip/system_testDelay_0_7/system_testDelay_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testDelay_0_7 || ORIG_REF_NAME==system_testDelay_0_7}]

# IP: bd/system/ip/system_testPulser_0_9/system_testPulser_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_9 || ORIG_REF_NAME==system_testPulser_0_9}]

# IP: bd/system/ip/system_testPulser_0_10/system_testPulser_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_0_10 || ORIG_REF_NAME==system_testPulser_0_10}]

# IP: bd/system/ip/system_testPulser_1_11/system_testPulser_1_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_testPulser_1_11 || ORIG_REF_NAME==system_testPulser_1_11}]

# IP: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_generator_0_0 || ORIG_REF_NAME==system_fifo_generator_0_0}]

# IP: bd/system/ip/system_fifo_readout_0_0/system_fifo_readout_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_readout_0_0 || ORIG_REF_NAME==system_fifo_readout_0_0}]

# IP: bd/system/ip/system_counter_0_0/system_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_counter_0_0 || ORIG_REF_NAME==system_counter_0_0}]

# IP: bd/system/ip/system_oneshot_pulse_1_1/system_oneshot_pulse_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_oneshot_pulse_1_1 || ORIG_REF_NAME==system_oneshot_pulse_1_1}]

# IP: bd/system/ip/system_oneshot_pulse_0_2/system_oneshot_pulse_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_oneshot_pulse_0_2 || ORIG_REF_NAME==system_oneshot_pulse_0_2}]

# IP: bd/system/ip/system_TrigWordDelay_0_0/system_TrigWordDelay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_TrigWordDelay_0_0 || ORIG_REF_NAME==system_TrigWordDelay_0_0}]

# IP: bd/system/ip/system_implement_gtid_0_0/system_implement_gtid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_implement_gtid_0_0 || ORIG_REF_NAME==system_implement_gtid_0_0}]

# IP: bd/system/ip/system_auto_cc_5_0/system_auto_cc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_5 || ORIG_REF_NAME==system_auto_cc_5}]

# IP: bd/system/ip/system_buttonTrigger_0_0/system_buttonTrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_buttonTrigger_0_0 || ORIG_REF_NAME==system_buttonTrigger_0_0}]

# IP: bd/system/ip/system_ShiftRegisters_0_0/system_ShiftRegisters_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ShiftRegisters_0_0 || ORIG_REF_NAME==system_ShiftRegisters_0_0}]

# IP: bd/system/ip/system_triggers_0_0/system_triggers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_triggers_0_0 || ORIG_REF_NAME==system_triggers_0_0}]

# IP: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}]

# IP: bd/system/ip/system_auto_pc_44_0/system_auto_pc_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_44 || ORIG_REF_NAME==system_auto_pc_44}]

# IP: bd/system/ip/system_auto_cc_348/system_auto_cc_348.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_348 || ORIG_REF_NAME==system_auto_cc_348}]

# IP: bd/system/ip/system_auto_cc_353/system_auto_cc_353.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_353 || ORIG_REF_NAME==system_auto_cc_353}]

# IP: bd/system/ip/system_auto_cc_361/system_auto_cc_361.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_361 || ORIG_REF_NAME==system_auto_cc_361}]

# IP: bd/system/ip/system_auto_cc_363/system_auto_cc_363.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_363 || ORIG_REF_NAME==system_auto_cc_363}]

# IP: bd/system/ip/system_auto_cc_365/system_auto_cc_365.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_365 || ORIG_REF_NAME==system_auto_cc_365}]

# IP: bd/system/ip/system_tier2_xbar_0_1295/system_tier2_xbar_0_1295.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_1295 || ORIG_REF_NAME==system_tier2_xbar_0_1295}]

# IP: bd/system/ip/system_tier2_xbar_1_1296/system_tier2_xbar_1_1296.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_1296 || ORIG_REF_NAME==system_tier2_xbar_1_1296}]

# IP: bd/system/ip/system_tier2_xbar_2_1297/system_tier2_xbar_2_1297.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_1297 || ORIG_REF_NAME==system_tier2_xbar_2_1297}]

# IP: bd/system/ip/system_auto_cc_376/system_auto_cc_376.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_376 || ORIG_REF_NAME==system_auto_cc_376}]

# IP: bd/system/ip/system_auto_cc_377/system_auto_cc_377.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_377 || ORIG_REF_NAME==system_auto_cc_377}]

# IP: bd/system/ip/system_auto_cc_378/system_auto_cc_378.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_378 || ORIG_REF_NAME==system_auto_cc_378}]

# IP: bd/system/ip/system_auto_cc_379/system_auto_cc_379.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_379 || ORIG_REF_NAME==system_auto_cc_379}]

# IP: bd/system/ip/system_auto_cc_380/system_auto_cc_380.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_380 || ORIG_REF_NAME==system_auto_cc_380}]

# IP: bd/system/ip/system_auto_pc_74/system_auto_pc_74.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_74 || ORIG_REF_NAME==system_auto_pc_74}]

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0/system_fifo_generator_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_generator_0_0 || ORIG_REF_NAME==system_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0/system_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_fifo_generator_0_0 || ORIG_REF_NAME==system_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_fifo_generator_0_0/system_fifo_generator_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_5_0/system_auto_cc_5_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_5_0/system_auto_cc_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_5 || ORIG_REF_NAME==system_auto_cc_5}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_OOC.xdc

# XDC: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_tier2_xbar_0_1295/system_tier2_xbar_0_1295_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_1_1296/system_tier2_xbar_1_1296_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_2_1297/system_tier2_xbar_2_1297_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_376/system_auto_cc_376_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_376/system_auto_cc_376_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_376 || ORIG_REF_NAME==system_auto_cc_376}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_377/system_auto_cc_377_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_377/system_auto_cc_377_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_377 || ORIG_REF_NAME==system_auto_cc_377}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_378/system_auto_cc_378_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_378/system_auto_cc_378_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_378 || ORIG_REF_NAME==system_auto_cc_378}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_379/system_auto_cc_379_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_379/system_auto_cc_379_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_379 || ORIG_REF_NAME==system_auto_cc_379}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_cc_380/system_auto_cc_380_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_380/system_auto_cc_380_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_380 || ORIG_REF_NAME==system_auto_cc_380}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_74/system_auto_pc_74_ooc.xdc

# XDC: bd/system/system_ooc.xdc
