# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl {
  C:/Users/HEP/project_tubii/testDelay_1.0/hdl/testDelay_v1_0_S00_AXI.vhd
  C:/Users/HEP/project_tubii/testDelay_1.0/hdl/testDelay_v1_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/HEP/project_tubii/edit_testDelay_v1_0.data/wt [current_project]
set_property parent.project_dir C:/Users/HEP/project_tubii [current_project]
synth_design -top testDelay_v1_0 -part xc7z010clg400-1
write_checkpoint testDelay_v1_0.dcp
report_utilization -file testDelay_v1_0_utilization_synth.rpt -pb testDelay_v1_0_utilization_synth.pb
