# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/ShiftRegisters_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/buttonTrigger_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/implement_gtid_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/TrigWordDelay_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/oneshot_pulse_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/fifo_readout_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/counter_1.0
  c:/Users/Ian/project_tubii_7020/ShiftRegs_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/countDisplay_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/comboTrigger_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/testPulser_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/triggerOut_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/clockLogic_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/triggerSplit_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/testDelay_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/prescaleTrigger_1.0
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/burstTrigger_1.0
} [current_fileset]
read_vhdl {
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/triggerOut_1.0/hdl/triggerOut_v1_0_S00_AXI.vhd
  c:/Users/Ian/Documents/GitHub/project_tubii_7020/triggerOut_1.0/hdl/triggerOut_v1_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ian/Documents/GitHub/project_tubii_7020/triggerOut_1.0/triggerOut_v1_0_project/triggerOut_v1_0_project.data/wt [current_project]
set_property parent.project_dir C:/Users/Ian/Documents/GitHub/project_tubii_7020/triggerOut_1.0/triggerOut_v1_0_project [current_project]
synth_design -top triggerOut_v1_0 -part xc7z020clg400-1
write_checkpoint triggerOut_v1_0.dcp
report_utilization -file triggerOut_v1_0_utilization_synth.rpt -pb triggerOut_v1_0_utilization_synth.pb
